services:
  wechat-md-server:
    image: your-namespace/wechat-md-server:latest
    container_name: wechat-md-server
    user: "0:0"
    restart: unless-stopped
    environment:
      WECHAT_MD_APP_MASTER_KEY: "jlkjwerlkj!dljflksajdflk#dflksjdlkf@dsdlfj@jdfsdlkf"
      WECHAT_MD_ADMIN_USERNAME: "admin"
      WECHAT_MD_ADMIN_PASSWORD: "admin"
      WECHAT_MD_SESSION_COOKIE_SECURE: "true"
      WECHAT_MD_RUNTIME_CONFIG_PATH: "/app/data/runtime-config.json"
      WECHAT_MD_DEFAULT_OUTPUT_DIR: "/app/data/workdir-output"
    ports:
      - "8765:8765"
    volumes:
      - ./data:/app/data
